import {
  Asset,
  MaintenanceRecord,
  WarrantyRecord,
  DocumentRecord,
  ExpenseRecord,
  AppNotification,
  User,
  AppSettings,
} from '@/types';

export const DEMO_USER: User = {
  id: 'usr-demo-01',
  name: 'สมชาย มั่นคง',
  email: 'somchai@hometrack.th',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  createdAt: '2026-01-01',
};

export const DEMO_SETTINGS: AppSettings = {
  userId: 'usr-demo-01',
  householdName: 'บ้านสุขุมวิท 71 & ทรัพย์สินครอบครัว',
  currency: 'THB',
  reminderDays: [30, 14, 7, 3, 1, 0],
  language: 'th',
  theme: 'light',
};

export const DEMO_ASSETS: Asset[] = [
  {
    id: 'asset-car-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-car',
    name: 'Toyota Camry 2.5 Premium',
    brand: 'Toyota',
    model: 'Camry 2.5 HV Premium Luxury',
    serialNumber: 'TYT-CAM-2024-88912',
    purchaseDate: '2024-03-15',
    purchasePrice: 1799000,
    location: 'โรงจอดรถหน้าบ้าน',
    vendor: 'Toyota Buzz พระราม 9',
    installationDate: '2024-03-20',
    warrantyStart: '2024-03-15',
    warrantyEnd: '2029-03-15',
    warrantyProvider: 'Toyota Motor Thailand (5 ปี / 150,000 km)',
    insuranceStart: '2025-10-28',
    insuranceEnd: '2026-10-28', // Expiring in 22 days!
    insuranceProvider: 'วิริยะประกันภัย ชั้น 1',
    notes: 'รถยนต์ประจำบ้าน เติมน้ำมัน Gasohol 95 เข้าศูนย์ตามระยะทุก 10,000 km',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop&q=80',
    isVehicle: true,
    licensePlate: '9กข 4567 กทม.',
    vin: 'MR0BA3FK8P1239988',
    vehicleYear: 2024,
    currentMileage: 48500,
    mileageUpdatedAt: '2026-10-01',
    createdAt: '2024-03-15',
    updatedAt: '2026-10-01',
  },
  {
    id: 'asset-ac-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-ac',
    name: 'Daikin Air Conditioner — Living Room',
    brand: 'Daikin',
    model: 'Inverter FTKZ18WV2S (18,100 BTU)',
    serialNumber: 'DK-2024-99812-LR',
    purchaseDate: '2024-04-10',
    purchasePrice: 38900,
    location: 'ห้องนั่งเล่น ชั้น 1',
    vendor: 'HomePro เอกมัย',
    installationDate: '2024-04-12',
    warrantyStart: '2024-04-10',
    warrantyEnd: '2027-04-10',
    warrantyProvider: 'สยามไดกิ้น เซลส์',
    notes: 'แอร์ห้องนั่งเล่น เปิดทุกวันช่วงบ่าย-ค่ำ ล้างฟิลเตอร์ทุกเดือน ล้างใหญ่ทุก 6 เดือน',
    imageUrl: 'https://images.unsplash.com/photo-1614633833026-258055c5dfb5?w=800&auto=format&fit=crop&q=80',
    createdAt: '2024-04-10',
    updatedAt: '2026-04-15',
  },
  {
    id: 'asset-ac-02',
    userId: 'usr-demo-01',
    categoryId: 'cat-ac',
    name: 'Daikin Air Conditioner — Bedroom',
    brand: 'Daikin',
    model: 'Inverter FTKF12WV2S (12,300 BTU)',
    serialNumber: 'DK-2024-33421-MB',
    purchaseDate: '2024-04-10',
    purchasePrice: 24500,
    location: 'ห้องนอนใหญ่ ชั้น 2',
    vendor: 'HomePro เอกมัย',
    installationDate: '2024-04-12',
    warrantyStart: '2024-04-10',
    warrantyEnd: '2027-04-10',
    warrantyProvider: 'สยามไดกิ้น เซลส์',
    notes: 'เปิดเฉพาะตอนกลางคืน 25°C สภาพเงียบ ใช้งานปกติ',
    imageUrl: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800&auto=format&fit=crop&q=80',
    createdAt: '2024-04-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'asset-fridge-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-fridge',
    name: 'Samsung Refrigerator 2-Door Inverter',
    brand: 'Samsung',
    model: 'RT38K501JS8/ST (13.5 คิว)',
    serialNumber: 'SM-REF-2023-77124',
    purchaseDate: '2023-11-20',
    purchasePrice: 16990,
    location: 'ห้องครัว',
    vendor: 'Power Buy เซ็นทรัลพระราม 9',
    installationDate: '2023-11-22',
    warrantyStart: '2023-11-20',
    warrantyEnd: '2026-11-20', // Expiring in 45 days
    warrantyProvider: 'Samsung Electronics Thailand (คอมเพรสเซอร์ 10 ปี)',
    notes: 'Twin Cooling Plus กระจายความเย็นแยก 2 ส่วน ต้องเปลี่ยนไส้กรองดับกลิ่นทุก 6 เดือน',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
    createdAt: '2023-11-20',
    updatedAt: '2026-04-01',
  },
  {
    id: 'asset-washer-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-washer',
    name: 'LG Front Load Washing Machine',
    brand: 'LG',
    model: 'FV1450S2W (ซัก 10.5 kg / อบ 7 kg)',
    serialNumber: 'LG-WASH-2024-5519',
    purchaseDate: '2024-01-18',
    purchasePrice: 28900,
    location: 'ลานซักล้างหลังบ้าน',
    vendor: 'HomePro พระราม 9',
    installationDate: '2024-01-20',
    warrantyStart: '2024-01-18',
    warrantyEnd: '2026-10-31', // Expiring in 25 days!
    warrantyProvider: 'LG Electronics (มอเตอร์ Inverter Direct Drive 10 ปี)',
    notes: 'ซักผ้าสัปดาห์ละ 2-3 ครั้ง รันโปรแกรม Tub Clean ล้างถังซักทุก 3 เดือน',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
    createdAt: '2024-01-18',
    updatedAt: '2026-07-15',
  },
  {
    id: 'asset-heater-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-water-heater',
    name: 'Panasonic Water Heater Digital',
    brand: 'Panasonic',
    model: 'DH-3ND1TW (3500 Watts)',
    serialNumber: 'PNS-WH-2024-1189',
    purchaseDate: '2024-02-05',
    purchasePrice: 4890,
    location: 'ห้องน้ำชั้น 2 Master Bedroom',
    vendor: 'บุญถาวร รัชดา',
    installationDate: '2024-02-07',
    warrantyStart: '2024-02-05',
    warrantyEnd: '2029-02-05',
    warrantyProvider: 'พานาโซนิค เซลส์ (หม้อต้มทองแดง 5 ปี)',
    notes: 'มีระบบตัดไฟ ELB ตรวจเช็กปุ่ม Test สม่ำเสมอ',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    createdAt: '2024-02-05',
    updatedAt: '2026-02-05',
  },
  {
    id: 'asset-house-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-home',
    name: 'บ้านเดี่ยว 2 ชั้น (ระบบปั๊มน้ำ & หลังคา)',
    brand: 'Mitsubishi Electric (ปั๊มน้ำ) / SCG (หลังคา)',
    model: 'EP-305R (ปั๊มแรงดันคงที่ 300W)',
    serialNumber: 'HOUSE-SKV71-MAIN',
    purchaseDate: '2023-01-10',
    purchasePrice: 6850000,
    location: 'สุขุมวิท 71 แขวงคลองตันเหนือ',
    vendor: 'โครงการบ้านมัณฑนา',
    installationDate: '2023-01-10',
    warrantyStart: '2023-01-10',
    warrantyEnd: '2028-01-10',
    warrantyProvider: 'ประกันโครงสร้างบ้าน 5 ปี',
    insuranceStart: '2026-01-10',
    insuranceEnd: '2027-01-10',
    insuranceProvider: 'กรุงเทพประกันภัย (ประกันอัคคีภัย)',
    notes: 'ตรวจเช็กปั๊มน้ำและถังเก็บน้ำทุก 3 เดือน ฉีดพ่นปลวกทุก 6 เดือน',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80',
    createdAt: '2023-01-10',
    updatedAt: '2026-08-01',
  },
  {
    id: 'asset-tv-01',
    userId: 'usr-demo-01',
    categoryId: 'cat-tv',
    name: 'Sony Bravia 65" 4K OLED TV',
    brand: 'Sony',
    model: 'XR-65A80L (Cognitive Processor XR)',
    serialNumber: 'SNY-OLED-65-2023',
    purchaseDate: '2023-12-15',
    purchasePrice: 62900,
    location: 'ห้องนั่งเล่น ชั้น 1',
    vendor: 'Sony Store สยามพารากอน',
    installationDate: '2023-12-16',
    warrantyStart: '2023-12-15',
    warrantyEnd: '2026-12-15',
    warrantyProvider: 'Sony Thai (My Sony 3 ปี)',
    notes: 'ต่อเข้าชุดโฮมเธียเตอร์และ Apple TV 4K มีประกันจอเบิร์น',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
    createdAt: '2023-12-15',
    updatedAt: '2026-01-10',
  },
];

export const DEMO_MAINTENANCE: MaintenanceRecord[] = [
  // 1. Overdue Maintenance: Water filter replacement (Overdue by 3 days)
  {
    id: 'maint-overdue-01',
    userId: 'usr-demo-01',
    assetId: 'asset-fridge-01',
    title: 'เปลี่ยนไส้กรองดับกลิ่นและกรองน้ำดื่มตู้เย็น',
    type: 'maintenance',
    description: 'เปลี่ยนไส้กรอง Pure Taste Deodorizer และไส้กรองน้ำดื่มตามรอบ 6 เดือน',
    scheduledDate: '2026-10-03', // 3 days ago!
    status: 'scheduled', // overdue!
    priority: 'high',
    isRecurring: true,
    intervalValue: 6,
    intervalUnit: 'months',
    cost: 1200,
    provider: 'Samsung Service Center',
    notes: 'สั่งซื้ออะไหล่แท้จากศูนย์ไว้แล้ว รอเปลี่ยน',
    createdAt: '2026-04-03',
  },
  // 2. Upcoming Task 1: Clean Living Room AC (In 7 days: 2026-10-13)
  {
    id: 'maint-upcoming-01',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-01',
    title: 'ล้างแอร์ห้องนั่งเล่น (ล้างใหญ่ประจำรอบ 6 เดือน)',
    type: 'cleaning',
    description: 'ถอดล้างคอยล์เย็น คอยล์ร้อน เช็กระดับน้ำยา R32 ล้างท่อน้ำทิ้งและฉีดน้ำยาฆ่าเชื้อ',
    scheduledDate: '2026-10-13', // In 7 days
    status: 'scheduled',
    priority: 'medium',
    isRecurring: true,
    intervalValue: 6,
    intervalUnit: 'months',
    cost: 800,
    provider: 'ช่างสมหมาย แอร์เซอร์วิส (โทร 081-998-7766)',
    partsReplaced: [],
    notes: 'นัดหมายช่างช่วงเช้า 10:00 น.',
    createdAt: '2026-04-13',
  },
  // 3. Upcoming Task 2: Engine oil change Camry (In 15 days or 50,000 km)
  {
    id: 'maint-upcoming-02',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    title: 'เปลี่ยนน้ำมันเครื่องสังเคราะห์แท้ & เช็กระยะ 50,000 km',
    type: 'oil_change',
    description: 'ถ่ายน้ำมันเครื่องสังเคราะห์ 0W-20, เปลี่ยนไส้กรองน้ำมันเครื่อง, ตรวจเช็กระบบเบรกและของเหลว',
    scheduledDate: '2026-10-21', // In 15 days
    status: 'scheduled',
    priority: 'high',
    isRecurring: true,
    intervalValue: 6,
    intervalUnit: 'months',
    mileageInterval: 10000,
    dualTrigger: true, // Time OR Mileage!
    lastMileage: 40200,
    dueMileage: 50000,
    cost: 2500,
    provider: 'ศูนย์บริการ Toyota Buzz พระราม 9',
    partsReplaced: ['น้ำมันเครื่อง Toyota Synthetic 0W-20', 'ไส้กรองน้ำมันเครื่องแท้'],
    notes: 'ไมล์ปัจจุบัน 48,500 km เหลืออีก 1,500 km หรือถึงกำหนด 21 ต.ค. 2569',
    createdAt: '2026-04-21',
  },
  // 4. Upcoming Task 3: Water pump check (In 30 days: 2026-11-05)
  {
    id: 'maint-upcoming-03',
    userId: 'usr-demo-01',
    assetId: 'asset-house-01',
    title: 'ตรวจเช็กปั๊มน้ำ ถังเก็บน้ำ และแรงดันระบบประปา',
    type: 'inspection',
    description: 'ทดสอบการทำงานของสวิตช์แรงดันปั๊มน้ำ ตรวจรอยรั่วซึมท่อรอบบ้าน และทำความสะอาดตะแกรงกรอง',
    scheduledDate: '2026-11-05', // In 30 days
    status: 'scheduled',
    priority: 'low',
    isRecurring: true,
    intervalValue: 3,
    intervalUnit: 'months',
    cost: 500,
    provider: 'ช่างนพ ประปาและปั๊มน้ำ',
    notes: 'รอบตรวจเช็กไตรมาสที่ 4',
    createdAt: '2026-08-05',
  },
  // 5. Tub clean washing machine
  {
    id: 'maint-upcoming-04',
    userId: 'usr-demo-01',
    assetId: 'asset-washer-01',
    title: 'ล้างถังซักด้วยโปรแกรม Tub Clean และน้ำยาล้างคราบ',
    type: 'cleaning',
    description: 'ใช้น้ำยาล้างถังซัก LG แช่และรันโปรแกรมความร้อน 60°C',
    scheduledDate: '2026-10-25',
    status: 'scheduled',
    priority: 'low',
    isRecurring: true,
    intervalValue: 3,
    intervalUnit: 'months',
    cost: 250,
    provider: 'ดูแลเอง (DIY)',
    notes: 'ซื้อน้ำยาล้างเครื่องซักผ้าเตรียมไว้แล้ว',
    createdAt: '2026-07-25',
  },
  // 6. Completed Records (History)
  {
    id: 'maint-comp-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    title: 'เปลี่ยนผ้าเบรกหน้า-หลัง และเจียรจานเบรก',
    type: 'repair',
    description: 'เปลี่ยนผ้าเบรกแท้ Toyota และเจียรจานหน้าคู่',
    scheduledDate: '2026-08-15',
    completedDate: '2026-08-15',
    status: 'completed',
    priority: 'medium',
    isRecurring: false,
    cost: 4500,
    provider: 'B-Quik สาขาพัฒนาการ',
    mileage: 46200,
    partsReplaced: ['ผ้าเบรกหน้า Akebono', 'ผ้าเบรกหลังแท้'],
    notes: 'เบรกตอบสนองดี นุ่ม เงียบ',
    receiptDocumentId: 'doc-rcp-brake',
    createdAt: '2026-08-10',
  },
  {
    id: 'maint-comp-02',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    title: 'เปลี่ยนยางรถยนต์ 4 เส้น Michelin Primacy 4+',
    type: 'tire',
    description: 'ขนาดยาง 215/55R17 พร้อมถ่วงล้อและตั้งศูนย์คอมพิวเตอร์',
    scheduledDate: '2026-05-12',
    completedDate: '2026-05-12',
    status: 'completed',
    priority: 'high',
    isRecurring: true,
    intervalValue: 2,
    intervalUnit: 'years',
    cost: 18000,
    provider: 'Cockpit พัฒนาการ',
    mileage: 42100,
    partsReplaced: ['ยาง Michelin Primacy 4+ 215/55R17 จำนวน 4 เส้น'],
    notes: 'มียางรับประกัน 1 ปี บาด บวม แตก เคลมได้ฟรี',
    receiptDocumentId: 'doc-rcp-tires',
    createdAt: '2026-05-01',
  },
  {
    id: 'maint-comp-03',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-01',
    title: 'ล้างแอร์ห้องนั่งเล่น รอบต้นปี',
    type: 'cleaning',
    description: 'ล้างทำความสะอาดแอร์ใหญ่ ฉีดน้ำยาฆ่าเชื้อ',
    scheduledDate: '2026-04-13',
    completedDate: '2026-04-13',
    status: 'completed',
    priority: 'medium',
    isRecurring: true,
    intervalValue: 6,
    intervalUnit: 'months',
    nextDueDate: '2026-10-13',
    cost: 800,
    provider: 'ช่างสมหมาย แอร์เซอร์วิส',
    notes: 'แอร์เย็นฉ่ำ ไม่มีกลิ่นอับ',
    createdAt: '2026-04-10',
  },
  {
    id: 'maint-comp-04',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-02',
    title: 'ล้างแอร์ห้องนอนใหญ่ รอบต้นปี',
    type: 'cleaning',
    description: 'ล้างแอร์ห้องนอน ตรวจเช็กระบบไฟฟ้า',
    scheduledDate: '2026-05-10',
    completedDate: '2026-05-10',
    status: 'completed',
    priority: 'medium',
    isRecurring: true,
    intervalValue: 6,
    intervalUnit: 'months',
    nextDueDate: '2026-11-10',
    cost: 800,
    provider: 'ช่างสมหมาย แอร์เซอร์วิส',
    notes: 'รอบถัดไป พ.ย. 2569',
    createdAt: '2026-05-01',
  },
  {
    id: 'maint-comp-05',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    title: 'เปลี่ยนน้ำมันเครื่องสังเคราะห์แท้ 40,000 km',
    type: 'oil_change',
    description: 'เปลี่ยนน้ำมันเครื่อง ไส้กรอง และตรวจเช็ก 24 รายการ',
    scheduledDate: '2026-04-21',
    completedDate: '2026-04-21',
    status: 'completed',
    priority: 'high',
    isRecurring: true,
    intervalValue: 6,
    intervalUnit: 'months',
    mileageInterval: 10000,
    cost: 2500,
    provider: 'ศูนย์บริการ Toyota Buzz พระราม 9',
    mileage: 40200,
    partsReplaced: ['น้ำมันเครื่องสังเคราะห์ 0W-20', 'ไส้กรองน้ำมันเครื่อง'],
    notes: 'เข้าเช็กระยะตรงตามกำหนด',
    createdAt: '2026-04-15',
  },
];

export const DEMO_WARRANTIES: WarrantyRecord[] = [
  {
    id: 'war-camry-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    type: 'insurance',
    title: 'ประกันภัยรถยนต์ชั้น 1 ซ่อมห้าง',
    provider: 'วิริยะประกันภัย (Viriyah Insurance)',
    policyNumber: 'VRY-AUTO-8991204',
    startDate: '2025-10-28',
    endDate: '2026-10-28', // Expiring in 22 days!
    cost: 15000,
    coverageDetails: 'ทุนประกัน 1,100,000 บาท ซ่อมห้าง มีบริการช่วยเหลือฉุกเฉิน 24 ชม.',
    contactNumber: '1557',
    notes: 'ตัวแทนประกันติดต่อแจ้งเตือนต่ออายุแล้ว เตรียมชำระเบี้ยต่ออายุสัปดาห์หน้า',
    documentId: 'doc-ins-camry',
    createdAt: '2025-10-20',
  },
  {
    id: 'war-camry-tax',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    type: 'tax',
    title: 'ภาษีรถยนต์ประจำปี + พ.ร.บ.',
    provider: 'กรมการขนส่งทางบก / ทิพยประกันภัย',
    policyNumber: 'TAX-2569-CAMRY',
    startDate: '2025-11-15',
    endDate: '2026-11-15', // Expiring in 40 days
    cost: 2850,
    coverageDetails: 'ภาษีรถยนต์ 2,205 บาท + พ.ร.บ. คุ้มครองผู้ประสบภัย 645.21 บาท',
    contactNumber: '1584',
    notes: 'สามารถชำระภาษีล่วงหน้าผ่าน DLT e-Service ได้ 90 วัน',
    documentId: 'doc-veh-tax',
    createdAt: '2025-11-10',
  },
  {
    id: 'war-washer-01',
    userId: 'usr-demo-01',
    assetId: 'asset-washer-01',
    type: 'warranty',
    title: 'การรับประกันเครื่องซักผ้าและตัวถัง',
    provider: 'LG Electronics Thailand',
    policyNumber: 'LG-WTY-778104',
    startDate: '2024-01-18',
    endDate: '2026-10-31', // Expiring in 25 days!
    cost: 0,
    coverageDetails: 'รับประกันตัวเครื่อง 2 ปี (ส่วนมอเตอร์ Inverter รับประกัน 10 ปี ถึง 2034)',
    contactNumber: '02-878-5757',
    notes: 'ประกันตัวเครื่องจะหมดปลายเดือน ตรวจสภาพก่อนหมดสิทธิ์ฟรี',
    createdAt: '2024-01-18',
  },
  {
    id: 'war-ac-01',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-01',
    type: 'warranty',
    title: 'การรับประกันแอร์ไดกิ้น ห้องนั่งเล่น',
    provider: 'Siam Daikin Sales Co., Ltd.',
    policyNumber: 'DK-WTY-2024-9981',
    startDate: '2024-04-10',
    endDate: '2027-04-10', // Active
    cost: 0,
    coverageDetails: 'รับประกันแผงคอยล์ 3 ปี คอมเพรสเซอร์ 5 ปี อะไหล่ทุกชิ้นส่วน 1 ปี',
    contactNumber: '1271',
    notes: 'ลงทะเบียนออนไลน์เรียบร้อย ได้รับขยายเวลารับประกันเพิ่ม',
    documentId: 'doc-wty-daikin',
    createdAt: '2024-04-10',
  },
  {
    id: 'war-fridge-01',
    userId: 'usr-demo-01',
    assetId: 'asset-fridge-01',
    type: 'warranty',
    title: 'การรับประกันตู้เย็น Samsung',
    provider: 'Samsung Care+',
    policyNumber: 'SM-CARE-2023-77',
    startDate: '2023-11-20',
    endDate: '2026-11-20', // Expiring in 45 days
    cost: 0,
    coverageDetails: 'รับประกันตัวเครื่อง 3 ปี ดิจิทัลอินเวอร์เตอร์คอมเพรสเซอร์ 10 ปี',
    contactNumber: '1282',
    notes: 'มีบริการตรวจเช็กถึงบ้านฟรี',
    createdAt: '2023-11-20',
  },
  {
    id: 'war-house-01',
    userId: 'usr-demo-01',
    assetId: 'asset-house-01',
    type: 'insurance',
    title: 'กรมธรรม์ประกันอัคคีภัยและภัยธรรมชาติ',
    provider: 'กรุงเทพประกันภัย (Bangkok Insurance)',
    policyNumber: 'BKI-FIRE-2026-900',
    startDate: '2026-01-10',
    endDate: '2027-01-10', // Active
    cost: 4200,
    coverageDetails: 'วงเงินคุ้มครองสิ่งปลูกสร้างและทรัพย์สินภายใน 5,000,000 บาท',
    contactNumber: '1620',
    notes: 'คุ้มครองไฟไหม้ ฟ้าผ่า น้ำท่วม และโจรกรรม',
    createdAt: '2026-01-05',
  },
];

export const DEMO_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'doc-ins-camry',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    name: 'กรมธรรม์ประกันภัยรถยนต์ชั้น 1 วิริยะประกันภัย (Camry)',
    category: 'insurance_policy',
    fileType: 'pdf',
    fileSize: '2.4 MB',
    fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'VRY-POL-8991204',
    notes: 'กรมธรรม์ตัวจริงเก็บในแฟ้มรถ มีสำเนาติดไว้ในเก๊ะหน้ารถ',
    uploadedAt: '2025-10-28',
  },
  {
    id: 'doc-rcp-brake',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    name: 'ใบเสร็จค่าเปลี่ยนผ้าเบรก B-Quik',
    category: 'repair_invoice',
    fileType: 'jpg',
    fileSize: '820 KB',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'BQ-INV-20260815-99',
    notes: 'มีรับประกันงานซ่อม 6 เดือน หรือ 10,000 km',
    uploadedAt: '2026-08-15',
  },
  {
    id: 'doc-rcp-tires',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    name: 'ใบเสร็จและใบรับประกันยาง Michelin 4 เส้น Cockpit',
    category: 'receipt',
    fileType: 'pdf',
    fileSize: '1.6 MB',
    fileUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'CKP-20260512-110',
    notes: 'รับสิทธิ์สลับยางถ่วงล้อฟรีทุก 10,000 km ที่ Cockpit',
    uploadedAt: '2026-05-12',
  },
  {
    id: 'doc-wty-daikin',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-01',
    name: 'คู่มือและใบรับประกันเครื่องปรับอากาศ Daikin FTKZ Series',
    category: 'manual',
    fileType: 'pdf',
    fileSize: '4.8 MB',
    fileUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'DK-MAN-FTKZ18',
    notes: 'คู่มือวิธีถอดล้างแผ่นกรองและตั้งค่าแอป Daikin Mobile Controller',
    uploadedAt: '2024-04-12',
  },
  {
    id: 'doc-fridge-rcp',
    userId: 'usr-demo-01',
    assetId: 'asset-fridge-01',
    name: 'ใบเสร็จและใบกำกับภาษีตู้เย็น Samsung Power Buy',
    category: 'receipt',
    fileType: 'png',
    fileSize: '1.1 MB',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'PB-INV-20231120-771',
    notes: 'เอกสารชำระผ่านบัตรเครดิต ผ่อน 0% 10 เดือน',
    uploadedAt: '2023-11-20',
  },
  {
    id: 'doc-washer-man',
    userId: 'usr-demo-01',
    assetId: 'asset-washer-01',
    name: 'คู่มือการใช้งานเครื่องซักผ้าฝาหน้า LG FV1450',
    category: 'manual',
    fileType: 'pdf',
    fileSize: '5.2 MB',
    fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'LG-MAN-FV1450',
    notes: 'คู่มือการแก้ไขรหัสแจ้งเตือนข้อผิดพลาด (Error Code)',
    uploadedAt: '2024-01-20',
  },
  {
    id: 'doc-veh-tax',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    name: 'สำเนาเล่มทะเบียนรถและป้ายวงกลมภาษีรถยนต์ (Camry)',
    category: 'vehicle_doc',
    fileType: 'jpg',
    fileSize: '950 KB',
    fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    invoiceNumber: 'DLT-TAX-2569-881',
    notes: 'ป้ายภาษีติดกระจกหน้ารถฝั่งซ้าย',
    uploadedAt: '2025-11-15',
  },
];

export const DEMO_EXPENSES: ExpenseRecord[] = [
  // This month (October 2026)
  {
    id: 'exp-2026-10-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    category: 'fuel',
    amount: 1800,
    date: '2026-10-02',
    description: 'เติมน้ำมัน Gasohol 95 เต็มถัง (Camry)',
    provider: 'ปตท. สเตชั่น พัฒนาการ',
    createdAt: '2026-10-02',
  },
  // Previous months in 2026
  {
    id: 'exp-2026-08-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    category: 'repair',
    amount: 4500,
    date: '2026-08-15',
    description: 'เปลี่ยนผ้าเบรกหน้า-หลัง และเจียรจานเบรก',
    provider: 'B-Quik สาขาพัฒนาการ',
    receiptDocumentId: 'doc-rcp-brake',
    maintenanceRecordId: 'maint-comp-01',
    createdAt: '2026-08-15',
  },
  {
    id: 'exp-2026-05-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    category: 'parts',
    amount: 18000,
    date: '2026-05-12',
    description: 'เปลี่ยนยางรถยนต์ Michelin Primacy 4+ (4 เส้น)',
    provider: 'Cockpit พัฒนาการ',
    receiptDocumentId: 'doc-rcp-tires',
    maintenanceRecordId: 'maint-comp-02',
    createdAt: '2026-05-12',
  },
  {
    id: 'exp-2026-05-02',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-02',
    category: 'maintenance',
    amount: 800,
    date: '2026-05-10',
    description: 'ล้างแอร์ห้องนอนใหญ่ รอบต้นปี',
    provider: 'ช่างสมหมาย แอร์เซอร์วิส',
    maintenanceRecordId: 'maint-comp-04',
    createdAt: '2026-05-10',
  },
  {
    id: 'exp-2026-04-01',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-01',
    category: 'maintenance',
    amount: 800,
    date: '2026-04-13',
    description: 'ล้างแอร์ห้องนั่งเล่น รอบต้นปี',
    provider: 'ช่างสมหมาย แอร์เซอร์วิส',
    maintenanceRecordId: 'maint-comp-03',
    createdAt: '2026-04-13',
  },
  {
    id: 'exp-2026-04-02',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    category: 'maintenance',
    amount: 2500,
    date: '2026-04-21',
    description: 'เปลี่ยนน้ำมันเครื่องสังเคราะห์แท้ 40,000 km',
    provider: 'ศูนย์บริการ Toyota Buzz พระราม 9',
    maintenanceRecordId: 'maint-comp-05',
    createdAt: '2026-04-21',
  },
  {
    id: 'exp-2026-01-01',
    userId: 'usr-demo-01',
    assetId: 'asset-house-01',
    category: 'insurance',
    amount: 4200,
    date: '2026-01-10',
    description: 'เบี้ยประกันอัคคีภัยบ้านเดี่ยว ประจำปี 2569',
    provider: 'กรุงเทพประกันภัย',
    createdAt: '2026-01-10',
  },
  {
    id: 'exp-2025-10-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    category: 'insurance',
    amount: 15000,
    date: '2025-10-28',
    description: 'เบี้ยประกันภัยรถยนต์ชั้น 1 วิริยะประกันภัย (Camry)',
    provider: 'วิริยะประกันภัย',
    receiptDocumentId: 'doc-ins-camry',
    createdAt: '2025-10-28',
  },
  {
    id: 'exp-2025-11-01',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    category: 'tax',
    amount: 2850,
    date: '2025-11-15',
    description: 'ต่อภาษีรถยนต์ประจำปี + พ.ร.บ. (Camry)',
    provider: 'กรมการขนส่งทางบก',
    receiptDocumentId: 'doc-veh-tax',
    createdAt: '2025-11-15',
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    userId: 'usr-demo-01',
    assetId: 'asset-fridge-01',
    type: 'maintenance',
    title: '⚠️ เลยกำหนด: เปลี่ยนไส้กรองดับกลิ่นตู้เย็น Samsung',
    message: 'เลยกำหนดมาแล้ว 3 วัน (กำหนดเดิม 3 ต.ค. 2569) กรุณาตรวจสอบหรือเปลี่ยนไส้กรอง',
    dueDate: '2026-10-03',
    status: 'overdue',
    isRead: false,
    actionUrl: '/assets/asset-fridge-01',
    createdAt: '2026-10-04',
  },
  {
    id: 'notif-02',
    userId: 'usr-demo-01',
    assetId: 'asset-ac-01',
    type: 'maintenance',
    title: '❄️ อีก 7 วัน: ล้างแอร์ห้องนั่งเล่น Daikin',
    message: 'ถึงรอบล้างใหญ่ 6 เดือน ในวันที่ 13 ต.ค. 2569 ติดต่อช่างสมหมาย 081-998-7766',
    dueDate: '2026-10-13',
    status: 'upcoming',
    isRead: false,
    actionUrl: '/assets/asset-ac-01',
    createdAt: '2026-10-06',
  },
  {
    id: 'notif-03',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    type: 'maintenance',
    title: '🚗 อีก 15 วัน: เปลี่ยนน้ำมันเครื่อง Toyota Camry',
    message: 'ครบกำหนดเช็กระยะ 50,000 km ในวันที่ 21 ต.ค. 2569 หรืออีก 1,500 km',
    dueDate: '2026-10-21',
    status: 'upcoming',
    isRead: false,
    actionUrl: '/assets/asset-car-01',
    createdAt: '2026-10-06',
  },
  {
    id: 'notif-04',
    userId: 'usr-demo-01',
    assetId: 'asset-car-01',
    type: 'insurance',
    title: '🛡️ อีก 22 วัน: ประกันภัยรถยนต์ชั้น 1 วิริยะประกันภัย จะหมดอายุ',
    message: 'กรมธรรม์ VRY-AUTO-8991204 จะหมดอายุในวันที่ 28 ต.ค. 2569 กรุณาต่ออายุก่อนสิ้นสุดความคุ้มครอง',
    dueDate: '2026-10-28',
    status: 'upcoming',
    isRead: false,
    actionUrl: '/warranty',
    createdAt: '2026-10-06',
  },
  {
    id: 'notif-05',
    userId: 'usr-demo-01',
    assetId: 'asset-washer-01',
    type: 'warranty',
    title: '🧺 อีก 25 วัน: ประกันตัวเครื่อง LG Washing Machine จะหมดอายุ',
    message: 'การรับประกันตัวเครื่องจะสิ้นสุดวันที่ 31 ต.ค. 2569 (มอเตอร์ยังคุ้มครองถึงปี 2034)',
    dueDate: '2026-10-31',
    status: 'upcoming',
    isRead: true,
    actionUrl: '/assets/asset-washer-01',
    createdAt: '2026-10-01',
  },
  {
    id: 'notif-06',
    userId: 'usr-demo-01',
    assetId: 'asset-house-01',
    type: 'maintenance',
    title: '🏠 อีก 30 วัน: ตรวจเช็กปั๊มน้ำและระบบประปาบ้าน',
    message: 'ถึงรอบตรวจเช็กไตรมาสที่ 4 ในวันที่ 5 พ.ย. 2569',
    dueDate: '2026-11-05',
    status: 'upcoming',
    isRead: true,
    actionUrl: '/assets/asset-house-01',
    createdAt: '2026-10-06',
  },
];
